import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import Navbar from "@/components/Navbar";
import { auth } from "@/auth";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
  const username = session?.user?.name || session?.user?.email || "anon";

  return (
    <html lang="en" className="max-w-[1440px] mx-auto">
      <body className={`${inter.className}`} >
        <Navbar isLoggedIn={!!session} username={username} />
        {children}
      </body>
    </html>
  );
}
